version: '3.4'

services:
  csg.kaveri.userloginapi:
    image: csgkaveriuserloginapi:dev
    container_name: CSG.Kaveri.UserLoginAPI
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "CSG.Kaveri.UserLoginAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_csg.kaveri.userloginapi$
    volumes:
      - F:\Projects\CMS\Kaveri 2.0\Source\Kaveri\Services\Authentication\CSG.Kaveri.UserLoginAPI\CSG.Kaveri.UserLogin:/app
      - F:\Projects\CMS\Kaveri 2.0\Source\Kaveri\Services\Authentication\CSG.Kaveri.UserLoginAPI:/src
      - C:\Users\Administrator\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_csg.kaveri.userloginapi$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_csg.kaveri.userloginapi$ \"/app/bin/Debug/net5.0/CSG.Kaveri.UserLoginAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true